### PR TITLE
Remove Custom mlr3 defaults section

### PR DESCRIPTION
**Pull request by sebffischer**
Sometimes we introduce new parameters and this is mentioned in the "Custom mlr3 defaults" section, which is a misleading name

### CODE REVIEW

**Comment by pat-s** [comment]
"Custom mlr3 defaults" might not be the best wording but I actually like it more than "Parameter Changes" as the latter is quite undescriptive and general. As a user, I would not know what this means in this context.

Maybe something along the lines of "mlr3 parameter defaults which differ compared to upstream package" or similar?

**Comment by sebffischer** [comment]
My whole point is that the focus on "defaults" is wrong. I don't care about the wording, as long as it is semantically correct ,which it currently isn't (or the section is being misused).

**Comment by sebffischer** [comment]
E.g. in ranger, we introduce a new parameter "mtry".

**Comment by sebffischer** [comment]
This is what I meant in my initial explanation of the PR: "Sometimes we introduce new parameters ..."

This also happens in extralearners

**Comment by sebffischer** [comment]
Ok, I suggest adding a section "Custom mlr3 parameters"

**Comment by mllg** [comment]
Custom mlr3 parameters works for me. 

Do you agree with this change @RaphaelS1?

**Comment by RaphaelS1** [comment]
Yup sounds good

**Comment by pat-s** [comment]
While looking at it, I had the feeling that the difference between

- Custom mlr3 defaults
- Custom mlr3 parameters

might not be fully clear for users on the first look.
How about changing "Custom mlr3 parameters" to "additional parameters added by mlr3"?

**Comment by sebffischer** [comment]
Sometimes parameters are renamed (RWeka in extralearners) and this is currently also put in the "Custom mlr3 parameters". I think having it a little bit more generic is fine, otherwise we need too many sections.

**Comment by pat-s** [comment]
I was asking for a renaming of the section, not adding a third one. Was this a misunderstanding?

Maybe then "additional/renamed parameters by mlr3"?

**Comment by sebffischer** [comment]
The section is currently used to: 
* Mention when parameters were renamed
* Mention when we added parameters
You wanted to rename the section to "Additional parameters added by mlr3", which excludes the use for point 1. This would then require a new section, because I started this whole PR because of wrong section names. So this was our misunderstanding. 

I think the way it is now is good, all parameters also have additional explanations why they are listed in the respective section, so people should be smart enough to figure it out.

**Comment by sebffischer** [comment]
Also we already had 4 people agreeing on this so I don't think this needs any further discussion tbh

**Comment by pat-s** [comment]
It's an important change, worth discussing even multiple times imo.

> You wanted to rename the section to "Additional parameters added by mlr3", which excludes the use for point 1.This would then require a new section, because I started this whole PR because of wrong section names. So this was our misunderstanding.

Yes and no, that's why my last comment updated the wording again. So it would still stay at 2 different sections.

> I think the way it is now is good, all parameters also have additional explanations why they are listed in the respective section, so people should be smart enough to figure it out.

Fair enough, just wanted to help ;)

> so I don't think this needs any further discussion tbh

Didn't wanted to offend you or sound nagging.

**Comment by sebffischer** [comment]
Ups I hope I did not sound annoyed / offended but I just want to get done with this PR. If it is important to you feel free to take over and adjust it

**Comment by sebffischer** [comment]
Ok, I will be more patient next time! It is just that I already changed in twice in mlr3extralearners - probably I should have waited with that but I didn't...

**Pull request merged**
