### PR TITLE
SVM Implementation 

### PR DESCRIPTION
**Pull request by jakob-r**
- [x] scale to ParamUty
- [x] class weights
- [x] pass tests
- [ ] Dependencies (low prio!)

### CODE REVIEW

**Comment by mllg** [comment]
Note: You need to add "train" and/or "predict" tags for all parameters.

**Comment by mboecker** [comment]
classification svm is now done, I still want to add the regression svm though.

**Comment by mllg** [comment]
Looks good, thanks! I only did some minor cleanups (most of them are just a matter of taste).

The issue with the sanity task was a problem in the task itself (target variable was constant, fixed upstream in mlr3).

**Comment by mllg** [comment]
@mboecker If you want to be listed in the DESCRIPTION, please add yourself as a contributor in a new PR.

**Comment by jakob-r** [comment]
Short question: Whats the consensus about encoding dependencies for learners?

**Comment by mllg** [comment]
You mean dependencies / requirements of hyperparameters?

**Comment by jakob-r** [comment]
yes

**Pull request merged**
